<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>${groupId}</groupId>
    <artifactId>${rootArtifactId}</artifactId>
    <version>${version}</version>
  </parent>

  <groupId>${groupId}</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>${version}</version>
  <packaging>ear</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>

    <!-- EJB -->
    <dependency>
      <groupId>${groupId}</groupId>
      <artifactId>${rootArtifactId}-ejb</artifactId>
      <version>${version}</version>
      <type>ejb</type>
    </dependency>

    <!-- WAR -->
    <dependency>
      <groupId>${groupId}</groupId>
      <artifactId>${rootArtifactId}-web</artifactId>
      <version>${version}</version>
      <type>war</type>
    </dependency>

    <!-- TODO: Add Utility JARS -->

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ear-plugin</artifactId>
        <version>3.4.0</version>
        <configuration>
          <!-- Register the WAR -->
          <webModule>
            <groupId>${groupId}</groupId>
            <artifactId>${rootArtifactId}-web</artifactId>
          </webModule>
          <!-- Register the JAR as an EJB module -->
          <ejbModule>
            <groupId>${groupId}</groupId>
            <artifactId>${rootArtifactId}-ejb</artifactId>
          </ejbModule>
          <!-- TODO:  register utility EJB JARs -->
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.wildfly.plugins</groupId>
        <artifactId>wildfly-maven-plugin</artifactId>
        <version>5.0.0.Final</version> <!-- Use the latest version -->
        <executions>
          <!-- Undeploy the application on clean -->
          <execution>
            <id>undeploy</id>
            <phase>clean</phase>
            <goals>
              <goal>undeploy</goal>
            </goals>
            <configuration>
              <ignoreMissingDeployment>true</ignoreMissingDeployment>
            </configuration>
          </execution>
          <!-- Deploy the application on install -->
          <execution>
            <id>deploy</id>
            <phase>install</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>